routes/web.php
    Route::post('/assign/customer/deleteclient', 'TripCustomerController@deleteclient')->name('customer.trip.deleteclient');
    Route::post('/assign/customer/deletegroup', 'TripCustomerController@deletegroup')->name('customer.trip.deletegroup');

    Route::post('/assign/customer/addnewgroup', 'TripCustomerController@addnewgroup')->name('addnewgroup');

    Route::post('/assign/customer/getallclient', 'TripCustomerController@getallclient')->name('getallclient');

    Route::post('/client_category/sub_categories', 'TripCustomerController@getSubCategoriesWithCategory')->name('get.subcategories.category');
    Route::post('/sub_categories/clients', 'TripCustomerController@getClientWithSubCategory')->name('get.client.subcategories');

    Route::get('trip/customers/{id}', 'TripCustomerController@viewTripCustomer')->name('view.trip.customer');

    Route::post('trip/customers/customerbyid', 'TripCustomerController@viewTripByCustomerID')->name('view.trip.customer.customerbyid');

    Route::get('/trip/customer/current/step', 'TripCustomerController@changeCurrentStep')->name('change.customer.current.step');
    Route::post('/trip/all_customer/current/step', 'TripCustomerController@changeAllCustomerStep')->name('change.all.customer.current.step');
    Route::get('trip/customer/remove/{trip}', 'TripCustomerController@removeCustomer')->name('remove.customer.index');
    Route::post('trip/customer/remove', 'TripCustomerController@removeTripCustomer')->name('remove.customer.remove');

    //Route for customer hotel
    Route::get('trip/customers/hotel/{trip}', 'TripHotelController@viewTripCustomerHotel')->name('view.trip.customer.hotel');
    Route::post('trip/hotel', 'TripHotelController@assignHotelToTrip')->name('assign.hotel.trip');

    Route::delete('/trip/hotel/hoteldestroy/{id}', 'TripHotelController@hoteldestroy')->name('trip.hotel.hoteldestroy');

    Route::post('/trip/hotel/deletehotelbyid', 'TripHotelController@deletehotelbyid')->name('trip.hotel.deletehotelbyid');

    Route::get('trip/hotel/viewassignhotelclient/{hotelId}', 'TripHotelController@viewassignhotelclient')->name('trip.hotel.viewassignhotelclient');

    Route::post('trip/hotel/viewHotelTripByCustomerID', 'TripHotelController@viewHotelTripByCustomerID')->name('view.trip.hotel.viewHotelTripByCustomerID');

    Route::post('trip/customer/hotel', 'TripHotelController@assignHotelToSingleCustomer')->name('assign.hotel.single.customer');


    //Route::get('trip/test/{trip}', 'TripHotelController@test');

    //send push notification
    Route::get('/push_notification/{trip}', 'TripPushNotificationController@index')->name('trip.notification.index');
    Route::post('/push_notification', 'TripPushNotificationController@store')->name('trip.notification.store');

    //upload client with excel sheet
    Route::get('/excelupload', 'TripPushNotificationController@loadExcelView')->name('load.excel.view');
    Route::post('/excelupload/store', 'TripPushNotificationController@storeExcelSheet')->name('load.excel.store');
    Route::post('/excelupload/storestaff', 'TripPushNotificationController@storeExcelSheetForStaff')->name('load.excel.storestaff');

    Route::get('/excelupload/downloadclient', 'TripPushNotificationController@downloadclient')->name('load.excel.downloadclient');

    Route::get('/excelupload/downloadstaff', 'TripPushNotificationController@downloadstaff')->name('load.excel.downloadstaff');

    //Route for messages
    Route::get('trip/client/messages', 'TripMessageController@index')->name('trip.client.message');

    Route::post('load/client/message', 'TripMessageController@loadClientMessages')->name('load.client.message');

    Route::post('load/client', 'TripMessageController@loadClient')->name('load.client');

    Route::post('trip/client/messages', 'TripMessageController@showmessage')->name('trip.client.showmessage');

    Route::post('/send/messages', 'TripMessageController@sendMessages')->name('send.message');

    //Route for Trip airline
    Route::get('trip/flight/{trip}', 'TripFlightController@index')->name('trip.flight');
    Route::post('/trip/flight/store', 'TripFlightController@addFlightForTrip')->name('trip.flight.store');

    Route::get('trip/flight/viewassignclient/{flightid}', 'TripFlightController@viewassignclient')->name('trip.flight.viewassignclient');

    Route::delete('/trip/flight/destroy/{id}', 'TripFlightController@destroy')->name('trip.flight.destroy');

    Route::post('trip/flight/customerbyid', 'TripFlightController@viewTripByCustomerID')->name('view.trip.flight.customerbyid');
    Route::post('/trip/flight/customer/store', 'TripFlightController@updateFlightForCustomer')->name('trip.flight.customer.store');
    Route::post('/trip/flight/deleteflightbyid', 'TripFlightController@deleteflightbyid')->name('trip.flight.deleteflightbyid');

    //Route for trip tasks
    //Route::get('trip/task/{trip}', 'TripTaskController@index')->name('trip.task');
    Route::get('/trip/task/index', 'TripTaskController@index')->name('trip.task.index');
    Route::get('/trip/task/create', 'TripTaskController@create')->name('trip.task.create');
    Route::post('/trip/task/store', 'TripTaskController@addTasks')->name('trip.task.store');
    Route::delete('/trip/task/destroy/{id}', 'TripTaskController@destroy')->name('trip.task.destroy');
    Route::get('/trip/task/edit/{id}', 'TripTaskController@edit')->name('trip.task.edit');
    Route::post('/trip/task/update', 'TripTaskController@update')->name('trip.task.update');
    Route::get('/trip/task/stafftaskoverduedetail/{id}', 'TripTaskController@stafftaskoverduedetail')->name('trip.task.stafftaskoverduedetail');
    Route::get('/trip/task/customertaskoverduedetail/{id}', 'TripTaskController@customertaskoverduedetail')->name('trip.task.customertaskoverduedetail');


    // Route::post('/trip/custom/step_pack', 'TripStepController@assignCustomStepPackToTrip')->name('trip.customStepPack.store');

    //Route for Step Section
    Route::get('/step_pack/custom/{trip_id}', 'StepPackController@customStepPack')->name('customStepPack');

    Route::get('/step_pack/changestep/{trip_id}', 'StepPackController@changestep')->name('changestep');

    Route::post('/step_pack/changestep/storechangestep', 'StepPackController@storechangestep')->name('changestep.storechangestep');

    Route::get('step_pack/changestep/viewassignclient/{stepid}', 'StepPackController@viewassignclient')->name('changestep.viewassignclient');

    Route::delete('step_pack/changestep/destroy/{id}', 'StepPackController@destroy')->name('changestep.destroy');

    Route::post('step_pack/changestep/customerbyid', 'StepPackController@viewTripByCustomerID')->name('changestep.customerbyid');

    Route::post('/step_pack/custom/GetAllSteps', 'StepPackController@GetAllSteps')->name('GetAllSteps');
    Route::post('/step_pack/custom/SearchAllSteps', 'StepPackController@SearchAllSteps')->name('SearchAllSteps');
    Route::post('/step_pack/custom/AddSteps', 'TripStepController@AddSteps')->name('AddSteps');

    Route::post('/step_pack/custom/create', 'TripStepController@addCustomStepPack')->name('steppack.add');
    Route::post('/step_pack/custom/steps', 'StepPackController@addStepToStepPack')->name('steppack.step.add');

    Route::post('/step_pack/custom/deletechecklist', 'StepPackController@deletechecklist')->name('steppack.step.deletechecklist');

    Route::post('/step_pack/custom/deletesection', 'StepPackController@deletesection')->name('steppack.step.deletesection');

    Route::post('/step_pack/custom/CheckTotalStep', 'StepPackController@CheckTotalStep')->name('steppack.step.CheckTotalStep');

    Route::post('/step_pack/custom/deletestep', 'StepPackController@deletestep')->name('steppack.step.deletestep');
    Route::post('/step_pack/custom/deletestepvideo', 'StepPackController@deletestepVideo')->name('steppack.step.deletestepvideo');
    Route::post('/step/pack/steps', 'StepPackController@loadStepPackSteps')->name('steppack.steps');

    //Rooutes for trip guides
    Route::get('/trip/{trip_id}/guides', 'TripGuideController@index')->name('trip.guide.index');
    //Route::post('/trip/guides', 'TripGuideController@store')->name('trip.guide.store');
    //Route::get('/guides', 'GuideController@index')->name('guide.index');
    Route::post('/trip/guide', 'TripGuideController@store')->name('trip.guide.store');
    Route::delete('/trip/guide/{guide}', 'TripGuideController@destroy')->name('trip.guide.destroy');


    Route::prefix('ajax')->name('ajax.')->group(function () {
        Route::get('loadStepPacks/{travel_agency_id}', 'StepPackController@stepPacksByTravelAgency')->name('loadStepPacks')->middleware('super_admin');
        Route::post('/load/states', 'AjaxController@loadStates')->name('load.states');
        Route::post('/load/cities', 'AjaxController@loadCities')->name('load.cities');

    });

    //Route for Confirm Password
    Route::get('change_password', 'ChangePasswordController@index');
    Route::post('change_password', 'ChangePasswordController@update');

    //Route for Airlines
    Route::resource('airlines', 'AirlineController');

    //Route for Airport
    Route::resource('airports', 'AirportController');

    //Route for Staff
    Route::resource('staffs', 'StaffController');
    Route::get('/staffs/viewprofile/{staff_id}', 'StaffController@viewprofile')->name('staffs.viewprofile');
    Route::post('/staffs/search', 'StaffController@search')->name('staffs.search');
    Route::post('/staffs/ChangeStaffStatus', 'StaffController@ChangeStaffStatus')->name('staffs.ChangeStaffStatus');


    Route::get('/section/create', function () {
        return view('section/create');
    });
    Route::get('/section/index', function () {
        return Auth()->user();
    });
    Route::get('/section/show', function () {
        return view('section/show');
    });
    Route::get('/section/edit', function () {
        return view('section/edit');
    });

});

app/Airline.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Airline extends Model
{
    protected $guarded = [];

    public function scopeLoggedTravelAgency($query)
    {
        if (\Auth::user()->user_type == 'agent' || \Auth::user()->user_type == 'staff' || \Auth::user()->user_type == 'mobile_agent')
            return $query->where('travel_agency_id', \Auth::user()->userType->travel_agency_id);
        return $query;
    }

    public function travelAgency()
    {
    	return $this->belongsTo(TravelAgency::class);
    }
    public function country(){
    	return $this->belongsTo(Country::class);
    }

    public function state(){
    	return $this->belongsTo(State::class);
    }

    public function city(){
    	return $this->belongsTo(City::class);
    }
    public function flight()
    {
        return $this->hasMany(Flight::class,'id','airline_id');
    }

    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->setTimezone(\Auth::user()->time_zone);
    }

}

app/Http/Controllers/AirlineController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Airline;
use App\TravelAgency;
use App\Country;
use App\State;
use App\City;

class AirlineController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $airlines = Airline::loggedTravelAgency()->get();
        // $travelAgency = TravelAgency::all();
         
        return view('airlines.index', compact('airlines'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $airlines = Airline::all();
        $agencies = TravelAgency::all();
        $countries = Country::all();
        return view('airlines.create', compact('agencies', 'countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'              => 'required',
            'country'           => 'required',
        ]);

        $airline                    = new Airline;
        $airline->travel_agency_id     = Auth()->user()->userType->travelAgency->id;
        $airline->name                 = $request->name;
        $airline->country_id           = $request->country;
//        $airline->state_id             = $request->state;
//        $airline->city_id              = $request->city;
//        $airline->address              = $request->address;
//        $airline->phone_number         = $request->phone_number;

        $airline->save();

        return redirect(route('airlines.index'))->with(['status' => "success", 'message' => "Airline Added Successfully!"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $airline = Airline::findOrFail($id);
        return view('airlines.show', compact('airline'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $airline = Airline::findOrFail($id);
        $agencies = TravelAgency::all();
        $countries = Country::all();
//        $states = State::where('country_id', $airline->country_id)->get();
//        $cities = City::where('state_id', $airline->state_id)->get();
         return view('airlines.edit', compact('airline','agencies', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $this->validate($request,[
//            'travel_agency'     => 'required',
            'name'              => 'required',
            'country'           => 'required',
//            'state'             => 'required',
//            'city'              => 'required',
//            'address'           => 'required',
//            'phone_number'      => 'required'
        ]);
        $airline = Airline::findOrFail($id);
        $airline->update([
            'travel_agency_id' => Auth()->user()->userType->travelAgency->id,
            'name' => $request->name,
            'country_id' => $request->country,
//            'state_id' => $request->state,
//            'city_id' => $request->city,
//            'address' => $request->address,
//            'phone_number' => $request->phone_number
        ]);

        return redirect(route('airlines.index'))->with(['status' => "success", 'message' => "Airline Updated Successfully!"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $airline = Airline::findOrFail($id);
        $airline->delete();

        return redirect(route('airlines.index'))->with(['status' => "success", 'message' => "Airline Deleted Successfully!"]);
    }
}

resources/views/airlines/create.blade.php
@extends('adminlte::page')
@section('title', 'Create New Airline')
@section('content_header')
<h1>Create New Airline</h1>
<ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
    <div class="clearfix"></div>
@endsection
@section('content')
	<div class="box">
		<form action="{{ route('airlines.store') }}" method="POST">
			@csrf
		<div class="box-body">
			<div class="row">
				<div class="col-md-3">
					<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
						<label>Name <span>*</span></label>
						<input type="text" name="name" class="form-control" value="{{ old('name') }}">
						@if($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                        @endif
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group {{ $errors->has('country') ? 'has-error' : '' }}">
						<label>Country <span>*</span></label>
						<select class="form-control country" name="country" id="country" multiple="multiple">
							<option value="">Select</option>
							@foreach($countries as $country)
								<option value="{{ $country->id }}">{{ $country->name }}</option>
							@endforeach
						</select>
						@if($errors->has('country'))
                                <span class="help-block text-danger">{{ $errors->first('country') }}</span>
                        @endif
					</div>
				</div>
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('state') ? 'has-error' : '' }}">--}}
{{--						<label>State <span>*</span></label>--}}
{{--						<select class="form-control" name="state" id="state">--}}
{{--							<option value="">Select</option>--}}
{{--						</select>--}}
{{--						@if($errors->has('state'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('state') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('city') ? 'has-error' : '' }}">--}}
{{--						<label>Cities <span>*</span></label>--}}
{{--						<select class="form-control" name="city" id="city">--}}
{{--							<option value="">Select</option>--}}
{{--						</select>--}}
{{--						@if($errors->has('city'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('city') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">--}}
{{--						<label>Address <span>*</span></label>--}}
{{--						<input type="text" name="address" class="form-control" value="{{ old('address') }}">--}}
{{--						@if($errors->has('city'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('city') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('phone_number') ? 'has-error' : '' }}">--}}
{{--						<label>Phone No. <span>*</span></label>--}}
{{--						<input type="text" name="phone_number" class="form-control" value="{{ old('phone_number') }}">--}}
{{--						@if($errors->has('phone_number'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('phone_number') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
			</div>
		</div>
		<div class="box-footer text-center">
			<button type="submit" class="btn btn-primary btnSubmit">Create</button>
		</div>
		</form>
	</div>
@endsection

@push('js')
<script type="text/javascript">
	$(".country").select2({
        maximumSelectionLength: 1,
        placeholder: "Select Country"//placeholder
   });
	$('#country').change(function () {
            var country_id = $(this).val();
			$.ajaxSetup({
				headers: {
					'X-CSRF-TOKEN': '{{ csrf_token() }}'
				}
			});
			$.ajax({
				url : "{{ route('ajax.load.states') }}",
				type: "POST",
				dataType: 'JSON',
				data: { country_id: country_id},
				success: function(response){
					var states = '';
					if(response.status == 'success'){
						console.log(response);
						$(response.states).each( function(i,d){
							states += '<option value="'+ d.id +'">'+ d.name +'</option>';
						});

						$("#state").html(states);
					}else{
						toastr['error']('Something went wrong.');
					}
				},
				error: function(error){
					toastr['error']('Something went wrong.');
				}
			});
        });

	$('#state').change(function () {
		var state_id = $(this).val();
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': '{{ csrf_token() }}'
			}
		});
		$.ajax({
			url : "{{ route('ajax.load.cities') }}",
			type: "POST",
			dataType: 'JSON',
			data: { state_id: state_id},
			success: function(response){
				console.log(response);
				var cities = '';
				if(response.status == 'success'){
					$(response.cities).each( function(i,d){
						cities += '<option value="'+ d.id +'">'+ d.name +'</option>';
					});

					$("#city").html(cities);
				}else{
					toastr['error']('Something went wrong.');
				}
			},
			error: function(error){
				toastr['error']('Something went wrong.');
			}
		});
	});
</script>
@endpush

resources/views/airlines/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Airline')
@section('content_header')
<h1>Edit Airline</h1>
<ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
    <div class="clearfix"></div>
@endsection
@section('content')
	<div class="box">
		<form action="{{ route('airlines.update', $airline->id) }}" method="POST">
			@csrf
			@method('PUT')
		<div class="box-body">
			<div class="row">
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('travel_agency') ? 'has-error' : '' }}">--}}
{{--						<label>Travel Agency <span>*</span></label>--}}
{{--						<select class="form-control" name="travel_agency">--}}
{{--							@foreach($agencies as $agency)--}}
{{--								<option value="{{ $agency->id }}">{{ $agency->agency_name  }}</option>--}}
{{--							@endforeach--}}
{{--						</select>--}}
{{--						@if($errors->has('travel_agency'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('travel_agency') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
				<div class="col-md-3">
					<div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
						<label>Name <span>*</span></label>
						<input type="text" name="name" class="form-control" value="{{ $airline->name }}">
						@if($errors->has('name'))
                                <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                        @endif
					</div>
				</div>
				<div class="col-md-3">
					<div class="form-group {{ $errors->has('country') ? 'has-error' : '' }}">
						<label>Country <span>*</span></label>
						<select class="form-control country" name="country" id="country" multiple="multiple">
							@foreach($countries as $country)
								<option value="{{ $country->id }}" {{ ($airline->country_id == $country->id ? 'selected' : '') }}>{{ $country->name }}</option>
							@endforeach
						</select>
						@if($errors->has('country'))
                                <span class="help-block text-danger">{{ $errors->first('country') }}</span>
                        @endif
					</div>
				</div>
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('state') ? 'has-error' : '' }}">--}}
{{--						<label>State <span>*</span></label>--}}
{{--						<select class="form-control" name="state" id="state">--}}
{{--							@foreach($states as $state)--}}
{{--								<option value="{{ $state->id }}" {{ ($airline->state_id == $state->id ? 'selected' : '') }}>{{ $state->name }}</option>--}}
{{--							@endforeach--}}
{{--						</select>--}}
{{--						@if($errors->has('state'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('state') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('city') ? 'has-error' : '' }}">--}}
{{--						<label>Cities <span>*</span></label>--}}
{{--						<select class="form-control" name="city" id="city">--}}
{{--							@foreach($cities as $city)--}}
{{--								<option value="{{ $city->id }}" {{ ($airline->city_id == $city->id ? 'selected' : '') }}>{{ $city->name }}</option>--}}
{{--							@endforeach--}}
{{--						</select>--}}
{{--						@if($errors->has('city'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('city') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('address') ? 'has-error' : '' }}">--}}
{{--						<label>Address <span>*</span></label>--}}
{{--						<input type="text" name="address" class="form-control" value="{{ $airline->address }}">--}}
{{--						@if($errors->has('city'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('city') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
{{--				<div class="col-md-3">--}}
{{--					<div class="form-group {{ $errors->has('phone_number') ? 'has-error' : '' }}">--}}
{{--						<label>Phone No. <span>*</span></label>--}}
{{--						<input type="text" name="phone_number" class="form-control" value="{{ $airline->phone_number }}">--}}
{{--						@if($errors->has('phone_number'))--}}
{{--                                <span class="help-block text-danger">{{ $errors->first('phone_number') }}</span>--}}
{{--                        @endif--}}
{{--					</div>--}}
{{--				</div>--}}
			</div>
		</div>
		<div class="box-footer text-center">
			<button type="submit" class="btn btn-primary btnSubmit">Update</button>
		</div>
		</form>
	</div>
@endsection
@push('js')
<script type="text/javascript">
	$(".country").select2({
        maximumSelectionLength: 1,
        placeholder: "Select Country"//placeholder
   });
	$('#country').change(function () {
            var country_id = $(this).val();
			$.ajaxSetup({
				headers: {
					'X-CSRF-TOKEN': '{{ csrf_token() }}'
				}
			});
			$.ajax({
				url : "{{ route('ajax.load.states') }}",
				type: "POST",
				dataType: 'JSON',
				data: { country_id: country_id},
				success: function(response){
					var states = '';
					if(response.status == 'success'){
						console.log(response);
						$(response.states).each( function(i,d){
							states += '<option value="'+ d.id +'">'+ d.name +'</option>';
						});

						$("#state").html(states);
					}else{
						toastr['error']('Something went wrong.');
					}
				},
				error: function(error){
					toastr['error']('Something went wrong.');
				}
			});
        });

	$('#state').change(function () {
		var state_id = $(this).val();
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': '{{ csrf_token() }}'
			}
		});
		$.ajax({
			url : "{{ route('ajax.load.cities') }}",
			type: "POST",
			dataType: 'JSON',
			data: { state_id: state_id},
			success: function(response){
				console.log(response);
				var cities = '';
				if(response.status == 'success'){
					$(response.cities).each( function(i,d){
						cities += '<option value="'+ d.id +'">'+ d.name +'</option>';
					});

					$("#city").html(cities);
				}else{
					toastr['error']('Something went wrong.');
				}
			},
			error: function(error){
				toastr['error']('Something went wrong.');
			}
		});
	});
</script>
@endpush

resources/views/airlines/show.blade.php
@extends('adminlte::page')
@section('title', 'Airline Details')

@section('content_header')
<h1>Airline Details</h1>
<ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
@endsection


@section('content')
  <div class="box">
            <div class="box-header">
              <a href="{{ route('airlines.create') }}" class="btn btn-primary">Add Airline</a>
            </div>
            <div class="box-body table-responsive no-padding">
              <table class="table table-bordered">
               <tbody>
                <tr>
                  <th>Travel Agency</th>
                  <td>{{ $airline->travelAgency->agency_name }}</td>
                </tr>
                <tr>
                  <th>Name</th>
                  <td>{{ $airline->name }}</td>
                </tr>
                <tr>
                  <th>Country</th>
                  <td>{{ $airline->country->name }}</td>
                </tr>
                <tr>
                  <th>State</th>
                  <td>{{ $airline->state->name }}</td>
                </tr>
                <tr>
                  <th>City</th>
                  <td>{{ $airline->city->name  }}</td>
                </tr>
                <tr>
                  <th>Address</th>
                  <td>{{ $airline->address }}</td>
                </tr>
                <tr>
                  <th>Phone Number</th>
                  <td>{{ $airline->phone_number }}</td>
                </tr>
              </tbody>
            </table>
            </div>
            <!-- /.box-body -->
          </div>
@endsection