routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Route::get('email-test', function(){

//$details ='azeemulrehman71@gmail.com';
// $details['email'] =['azeemulrehman71@gmail.com','jeremiah@creative-dots.com','azeem.devsleague@gmail.com',
//     'yasin@creative-dots.com',
//     'ahmer@creative-dots.com',
//     'adilmughal@creative-dots.com',
//     'nabeel@creative-dots.com',
//     'alihusnain@creative-dots.com'];
// dispatch(new App\Jobs\SendEmailJob($details));
//  dd('done');
//});

Route::get('/', function () {
    return view('welcome');
//    return view('auth.login');
})->name('welcome.index');


Auth::routes();
Route::middleware(['auth', 'disablepreventback'])->group(function () {
    Route::get('/message', 'DashboardController@message');
    Route::get('/LicenseExpriy', 'DashboardController@LicenseExpriy');
    Route::get('/home', 'DashboardController@index')->name('homepage');
    Route::get('/fcm/{id}', "DashboardController@registerFCM");
    Route::post('/SaveImageData', 'DashboardController@SaveImageData')->name('SaveImageData');
    Route::post('/ShowAdminImage', 'DashboardController@ShowAdminImage')->name('ShowAdminImage');
    Route::post('/useForSession', 'DashboardController@useForSession')->name('useForSession');
    Route::post('/usefortimezone', 'DashboardController@usefortimezone')->name('usefortimezone');
    //Route for Task New
    Route::get('staff/tasks', 'StaffTaskController@index')->name('staff.tasks.index');
    Route::post('staff/tasks', 'StaffTaskController@completeTask')->name('staff.task.complete');
});

Route::prefix('admin')->middleware(['auth', 'disablepreventback'])->group(function () {
    Route::resource('trips', 'TripController');
    Route::post('trips/statuscheck', 'TripController@statuscheck')->name('trips.statuscheck');
    Route::post('trips/search', 'TripController@search')->name('trips.search');
    Route::get('trips/staffdetail/{id}', 'TripController@staffdetail')->name('trips.staffdetail');
    Route::get('trips/customertripdetail/{id}', 'TripController@customertripdetail')->name('trips.customertripdetail');

    Route::post('/trips/ChangeTripQibla', 'TripController@ChangeTripQibla')->name('trips.ChangeTripQibla');

    Route::resource('travel_agency', 'TravelAgencyController');
    Route::resource('packages', 'PackagesController');
    Route::resource('step_pack', 'StepPackController');
    Route::resource('client_categories', 'ClientCategoryController');
    Route::resource('clients', 'ClientController');
    Route::post('/clients/search', 'ClientController@search')->name('clients.search');

    Route::get('/clients/showprofile/{id}', 'ClientController@showprofile')->name('clients.showprofile');

    Route::get('/clients/clientalert/{id}', 'ClientController@clientalert')->name('clients.clientalert');

    Route::get('/clients/clientcomplaint/{id}', 'ClientController@clientcomplaint')->name('clients.clientcomplaint');

    Route::post('/clients/ChangeClientStatus', 'ClientController@ChangeClientStatus')->name('clients.ChangeClientStatus');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Routes for user settings
    Route::post('/change/password', 'UserController@changePassword')->name('change.password');

    //Route for feedback categories
    Route::resource('/feedback/categories', 'FeedbackCategoriesController', ['names' => [
        'index' => 'feedback.categories.index',
        'create' => 'feedback.categories.create',
        'store' => 'feedback.categories.store',
        'edit' => 'feedback.categories.edit',
        'update' => 'feedback.categories.update',
        'destroy' => 'feedback.categories.destroy',
    ]
    ]);

    Route::resource('/countries', 'CountriesController', ['names' => [
        'index' => 'countries.index',
        'create' => 'countries.create',
        'store' => 'countries.store',
        'edit' => 'countries.edit',
        'update' => 'countries.update',
        'destroy' => 'countries.destroy',
    ]
    ]);

    Route::resource('/hotels', 'HotelController', ['names' => [
        'index' => 'hotels.index',
        'create' => 'hotels.create',
        'store' => 'hotels.store',
        'edit' => 'hotels.edit',
        'update' => 'hotels.update',
        'destroy' => 'hotels.destroy',
    ]
    ]);

    Route::get('/change_password/changepassword', 'ChangePasswordController@changepassword')->name('changepassword');

    Route::post('change_password/clientpassword', 'ChangePasswordController@clientpassword')->name('clientpassword');

    Route::post('change_password/staffpassword', 'ChangePasswordController@staffpassword')->name('staffpassword');

    //Route for feedback
    Route::get('/feedbacks', 'FeedbackController@index')->name('feedback.index');

    //Route for guide
    Route::get('/guides', 'GuideController@index')->name('guide.index');
    Route::get('/guide/create', 'GuideController@create')->name('guide.create');
    Route::post('/guide', 'GuideController@store')->name('guide.store');
    Route::delete('/guide/{guide}', 'GuideController@destroy')->name('guide.destroy');

    //Route For Client Sub Category
    Route::resource('client_sub_categories', 'ClientSubCategoryController');


    //Routes for Emergency Alerts
    Route::prefix('emergency_alert')->name('emergency_alert.')->group(function () {
        Route::get('/{type?}', 'EmergencyAlertController@index')->name('index');
        Route::put('/{id}', 'EmergencyAlertController@update')->name('update')->where('id', '[0-9]+');
    });

    //Route for Trip step
    Route::resource('steps', 'StepController');

    Route::get('/trip/step_pack/{trip_id}', 'StepPackController@getStepPacks')->name('getStepPacks');


    Route::post('/trip/step_pack', 'TripStepController@assignStepPackToTrip')->name('trip.steppack');
    //assign customer
    Route::get('/assign/customer/{id}', 'TripCustomerController@index')->name('customer.trip.index');
    Route::post('/assign/customer', 'TripCustomerController@store')->name('customer.trip.store');
    Route::post('/assign/updategroup', 'TripCustomerController@updategroup')->name('customer.trip.updategroup');

    Route::post('/assign/customer/deleteclient', 'TripCustomerController@deleteclient')->name('customer.trip.deleteclient');
    Route::post('/assign/customer/deletegroup', 'TripCustomerController@deletegroup')->name('customer.trip.deletegroup');

    Route::post('/assign/customer/addnewgroup', 'TripCustomerController@addnewgroup')->name('addnewgroup');

    Route::post('/assign/customer/getallclient', 'TripCustomerController@getallclient')->name('getallclient');

    Route::post('/client_category/sub_categories', 'TripCustomerController@getSubCategoriesWithCategory')->name('get.subcategories.category');
    Route::post('/sub_categories/clients', 'TripCustomerController@getClientWithSubCategory')->name('get.client.subcategories');

    Route::get('trip/customers/{id}', 'TripCustomerController@viewTripCustomer')->name('view.trip.customer');

    Route::post('trip/customers/customerbyid', 'TripCustomerController@viewTripByCustomerID')->name('view.trip.customer.customerbyid');

    Route::get('/trip/customer/current/step', 'TripCustomerController@changeCurrentStep')->name('change.customer.current.step');
    Route::post('/trip/all_customer/current/step', 'TripCustomerController@changeAllCustomerStep')->name('change.all.customer.current.step');
    Route::get('trip/customer/remove/{trip}', 'TripCustomerController@removeCustomer')->name('remove.customer.index');
    Route::post('trip/customer/remove', 'TripCustomerController@removeTripCustomer')->name('remove.customer.remove');

    //Route for customer hotel
    Route::get('trip/customers/hotel/{trip}', 'TripHotelController@viewTripCustomerHotel')->name('view.trip.customer.hotel');
    Route::post('trip/hotel', 'TripHotelController@assignHotelToTrip')->name('assign.hotel.trip');

    Route::delete('/trip/hotel/hoteldestroy/{id}', 'TripHotelController@hoteldestroy')->name('trip.hotel.hoteldestroy');

    Route::post('/trip/hotel/deletehotelbyid', 'TripHotelController@deletehotelbyid')->name('trip.hotel.deletehotelbyid');

    Route::get('trip/hotel/viewassignhotelclient/{hotelId}', 'TripHotelController@viewassignhotelclient')->name('trip.hotel.viewassignhotelclient');

    Route::post('trip/hotel/viewHotelTripByCustomerID', 'TripHotelController@viewHotelTripByCustomerID')->name('view.trip.hotel.viewHotelTripByCustomerID');

    Route::post('trip/customer/hotel', 'TripHotelController@assignHotelToSingleCustomer')->name('assign.hotel.single.customer');


    //Route::get('trip/test/{trip}', 'TripHotelController@test');

    //send push notification
    Route::get('/push_notification/{trip}', 'TripPushNotificationController@index')->name('trip.notification.index');
    Route::post('/push_notification', 'TripPushNotificationController@store')->name('trip.notification.store');

    //upload client with excel sheet
    Route::get('/excelupload', 'TripPushNotificationController@loadExcelView')->name('load.excel.view');
    Route::post('/excelupload/store', 'TripPushNotificationController@storeExcelSheet')->name('load.excel.store');
    Route::post('/excelupload/storestaff', 'TripPushNotificationController@storeExcelSheetForStaff')->name('load.excel.storestaff');

    Route::get('/excelupload/downloadclient', 'TripPushNotificationController@downloadclient')->name('load.excel.downloadclient');

    Route::get('/excelupload/downloadstaff', 'TripPushNotificationController@downloadstaff')->name('load.excel.downloadstaff');

    //Route for messages

app/StepPack.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class StepPack extends Model
{
    protected $guarded = [];
    /**
     * Scope a query to only include logged in users trips.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLoggedTravelAgency($query)
    {
    	if(\Auth::user()->user_type == 'agent' || \Auth::user()->user_type == 'staff' || \Auth::user()->user_type == 'mobile_agent')
        	return $query->where('travel_agency_id', \Auth::user()->userType->travel_agency_id);
        return $query;
    }
    
    public function steps()
    {
    	return $this->hasMany(Step::class);
    }

    public function travelAgency()
    {
        return $this->belongsTo(TravelAgency::class);
    }

    public function trips()
    {
        return $this->hasMany(Trip::class);
    }

    public function tripsteppack()
    {
        return $this->belongsToMany(Trip::class, 'trip_step_packs','trip_id','step_pack_id');
    }
    
}

resources/views/step_pack/create.blade.php
@extends('adminlte::page')
@section('title', 'Add Step Pack')

@section('content_header')
    <h1>Add Step Pack</h1>
    <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
@endsection


@section('content')
    <div class="box">
        <div class="box-header">
            {{-- <h3 class="box-title">Add Step Pack</h3> --}}
        </div>
        <form action="{{ route('step_pack.store') }}" method="post" role="form" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label>Step Pack Name <span>*</span></label>
                            <input type="text" class="form-control" name="title" placeholder="Enter Step Pack Name" value="{{ old('title') }}" required="">
                            @if($errors->has('title'))
                                <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label>Travel Agency <span>*</span></label>
                            <select name="travel_agency_id" class="form-control">
                                <option value="">Select Travel Agency</option>
                                @foreach($travel_agencies as $travel_agency)
                                    <option value="{{ $travel_agency->id }}">{{ $travel_agency->agency_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('title'))
                                <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnSubmit">Submit</button>
            </div>
            <form>
    </div>
@endsection

resources/views/step_pack/edit.blade.php
@extends('adminlte::page')
@section('title', 'Edit Step Pack')

@section('content_header')
    <h1>Edit Step Pack</h1>
    <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
@endsection


@section('content')
    <div class="box">
        <div class="box-header">
            {{-- <h3 class="box-title">Edit Step Pack</h3> --}}
        </div>
        <form action="{{ route('step_pack.update', $step_pack->id) }}" method="post" role="form" enctype="multipart/form-data">
            @csrf
            {{ method_field('PUT') }}
            <div class="box-body">
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label>Step Pack Name <span>*</span></label>
                            <input type="text" class="form-control" name="title" placeholder="Enter Step Pack Name" value="{{ $step_pack->title }}" required="">
                            @if($errors->has('title'))
                                <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                            <label>Travel Agency <span>*</span></label>
                            <select name="travel_agency_id" class="form-control">
                                <option value="">Select Travel Agency</option>
                                @foreach($travel_agencies as $travel_agency)
                                    <option value="{{ $travel_agency->id }}" {{ ($step_pack->travel_agency_id == $travel_agency->id) ? 'selected' : 'none' }}>{{ $travel_agency->agency_name }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('title'))
                                <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btnSubmit">Submit</button>
            </div>
            <form>
    </div>
@endsection

resources/views/step_pack/index.blade.php
@extends('adminlte::page')
@section('title', 'Trip Steps Pack')

@section('content_header')
	<h1>Trip Steps Pack</h1>
	{{-- <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol> --}}
@endsection


@section('content')
	<div class="box">
    <div class="box-header">
      <div class="col-md-6">
      	{{-- <h3 class="box-title">Trip Steps Pack</h3> --}}
      </div>
      <div class="col-md-6 text-right">
      	<a href="{{ route('step_pack.create') }}" class="btn btn-primary">Add Step Pack</a>
      </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <table id="travelAgency" class="table table-bordered table-striped">
        <thead>
        <tr>
        	<th>Sr#</th>
			@if(\Auth::user()->user_type == "super_admin")
				<th>Travel Agency</th>
			@endif
          	<th>Title</th>
          	<th>No. of Trips</th>
          	<th>Action</th>
        </tr>
        </thead>
        <tbody>
    	@foreach($step_packs as $step_pack)
	        <tr>
	          	<td>{{ $loop->iteration }}</td>
	          	@if(\Auth::user()->user_type == "super_admin")
					<td>
						<a href="{{ route('travel_agency.show', ['id' => $step_pack->travel_agency_id]) }}">{{ $step_pack->travelAgency->agency_name }}</a>
					</td>
				@endif
				<td>{{ $step_pack->title }}</td>
				<td>{{ $step_pack->trips->count() }}</td>
				<td>
					<a href="{{ route('step_pack.edit', ['id' => $step_pack->id]) }}"><button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i></button></a>
					{{-- <a href="{{ route('step_pack.show', ['id' => $step_pack->id]) }}"><button class="btn btn-xs btn-success" data-toggle="tooltip" title="View"><i class="fa fa-eye"></i></button></a> --}}
					<form action="{{ route('step_pack.destroy', ['id' => $step_pack->id]) }}" method="POST" class="delete_item">
						@csrf
						@method('DELETE')
						<button type="submit" class="btn btn-xs btn-danger" data-toggle="tooltip" title="Delete"><i class="fa fa-close"></i></button>
					</form>
				</td>
	        </tr>
        @endforeach
        </tbody>
      </table>
    </div>
    <!-- /.box-body -->
  </div>
@endsection

@push('js')
	<script type="text/javascript">
		 $(function () {
	    $('#stepPacks').DataTable({
	    	'lengthChange': false,
	    })

	  });
	</script>
@endpush

resources/views/step_pack/show.blade.php
@extends('adminlte::page')
@section('title', 'Step Pack Details')

@section('content_header')
<h1>Step Pack Details</h1>
<ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol>
@endsection


@section('content')
  <div class="box">
            <div class="box-header">
              <a href="{{ route('step_pack.create', $step_pack->id) }}" class="btn btn-primary">Add Step</a>
            </div>
            <div class="box-body table-responsive no-padding">
                <table class="table table-bordered">
                   <tbody>
                    <tr>
                      <th>Title</th>
                      <td>{{ $step_pack->title }}</td>
                    </tr>
                    <tr>
                      <th>No of Trips</th>
                      <td>{{  $step_pack->trips->count() }}</td>
                    </tr>
                  </tbody>
                </table>
            </div>
            <!-- /.box-body -->
  </div>
@endsection