routes/web.php
    Route::get('trips/customertripdetail/{id}', 'TripController@customertripdetail')->name('trips.customertripdetail');

    Route::post('/trips/ChangeTripQibla', 'TripController@ChangeTripQibla')->name('trips.ChangeTripQibla');

    Route::resource('travel_agency', 'TravelAgencyController');
    Route::resource('packages', 'PackagesController');
    Route::resource('step_pack', 'StepPackController');
    Route::resource('client_categories', 'ClientCategoryController');
    Route::resource('clients', 'ClientController');
    Route::post('/clients/search', 'ClientController@search')->name('clients.search');

    Route::get('/clients/showprofile/{id}', 'ClientController@showprofile')->name('clients.showprofile');

    Route::get('/clients/clientalert/{id}', 'ClientController@clientalert')->name('clients.clientalert');

    Route::get('/clients/clientcomplaint/{id}', 'ClientController@clientcomplaint')->name('clients.clientcomplaint');

    Route::post('/clients/ChangeClientStatus', 'ClientController@ChangeClientStatus')->name('clients.ChangeClientStatus');
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    //Routes for user settings
    Route::post('/change/password', 'UserController@changePassword')->name('change.password');

    //Route for feedback categories
    Route::resource('/feedback/categories', 'FeedbackCategoriesController', ['names' => [
        'index' => 'feedback.categories.index',
        'create' => 'feedback.categories.create',
        'store' => 'feedback.categories.store',
        'edit' => 'feedback.categories.edit',
        'update' => 'feedback.categories.update',
        'destroy' => 'feedback.categories.destroy',
    ]
    ]);

    Route::resource('/countries', 'CountriesController', ['names' => [
        'index' => 'countries.index',
        'create' => 'countries.create',
        'store' => 'countries.store',
        'edit' => 'countries.edit',
        'update' => 'countries.update',
        'destroy' => 'countries.destroy',
    ]
    ]);

    Route::resource('/hotels', 'HotelController', ['names' => [
        'index' => 'hotels.index',
        'create' => 'hotels.create',
        'store' => 'hotels.store',
        'edit' => 'hotels.edit',
        'update' => 'hotels.update',
        'destroy' => 'hotels.destroy',
    ]
    ]);

    Route::get('/change_password/changepassword', 'ChangePasswordController@changepassword')->name('changepassword');

    Route::post('change_password/clientpassword', 'ChangePasswordController@clientpassword')->name('clientpassword');

    Route::post('change_password/staffpassword', 'ChangePasswordController@staffpassword')->name('staffpassword');

    //Route for feedback
    Route::get('/feedbacks', 'FeedbackController@index')->name('feedback.index');

    //Route for guide
    Route::get('/guides', 'GuideController@index')->name('guide.index');
    Route::get('/guide/create', 'GuideController@create')->name('guide.create');
    Route::post('/guide', 'GuideController@store')->name('guide.store');
    Route::delete('/guide/{guide}', 'GuideController@destroy')->name('guide.destroy');

    //Route For Client Sub Category
    Route::resource('client_sub_categories', 'ClientSubCategoryController');


    //Routes for Emergency Alerts
    Route::prefix('emergency_alert')->name('emergency_alert.')->group(function () {
        Route::get('/{type?}', 'EmergencyAlertController@index')->name('index');
        Route::put('/{id}', 'EmergencyAlertController@update')->name('update')->where('id', '[0-9]+');
    });

    //Route for Trip step
    Route::resource('steps', 'StepController');

    Route::get('/trip/step_pack/{trip_id}', 'StepPackController@getStepPacks')->name('getStepPacks');


    Route::post('/trip/step_pack', 'TripStepController@assignStepPackToTrip')->name('trip.steppack');
    //assign customer
    Route::get('/assign/customer/{id}', 'TripCustomerController@index')->name('customer.trip.index');
    Route::post('/assign/customer', 'TripCustomerController@store')->name('customer.trip.store');
    Route::post('/assign/updategroup', 'TripCustomerController@updategroup')->name('customer.trip.updategroup');

    Route::post('/assign/customer/deleteclient', 'TripCustomerController@deleteclient')->name('customer.trip.deleteclient');
    Route::post('/assign/customer/deletegroup', 'TripCustomerController@deletegroup')->name('customer.trip.deletegroup');

    Route::post('/assign/customer/addnewgroup', 'TripCustomerController@addnewgroup')->name('addnewgroup');

    Route::post('/assign/customer/getallclient', 'TripCustomerController@getallclient')->name('getallclient');

    Route::post('/client_category/sub_categories', 'TripCustomerController@getSubCategoriesWithCategory')->name('get.subcategories.category');
    Route::post('/sub_categories/clients', 'TripCustomerController@getClientWithSubCategory')->name('get.client.subcategories');

    Route::get('trip/customers/{id}', 'TripCustomerController@viewTripCustomer')->name('view.trip.customer');

    Route::post('trip/customers/customerbyid', 'TripCustomerController@viewTripByCustomerID')->name('view.trip.customer.customerbyid');

    Route::get('/trip/customer/current/step', 'TripCustomerController@changeCurrentStep')->name('change.customer.current.step');
    Route::post('/trip/all_customer/current/step', 'TripCustomerController@changeAllCustomerStep')->name('change.all.customer.current.step');
    Route::get('trip/customer/remove/{trip}', 'TripCustomerController@removeCustomer')->name('remove.customer.index');
    Route::post('trip/customer/remove', 'TripCustomerController@removeTripCustomer')->name('remove.customer.remove');

    //Route for customer hotel
    Route::get('trip/customers/hotel/{trip}', 'TripHotelController@viewTripCustomerHotel')->name('view.trip.customer.hotel');
    Route::post('trip/hotel', 'TripHotelController@assignHotelToTrip')->name('assign.hotel.trip');

    Route::delete('/trip/hotel/hoteldestroy/{id}', 'TripHotelController@hoteldestroy')->name('trip.hotel.hoteldestroy');

    Route::post('/trip/hotel/deletehotelbyid', 'TripHotelController@deletehotelbyid')->name('trip.hotel.deletehotelbyid');

    Route::get('trip/hotel/viewassignhotelclient/{hotelId}', 'TripHotelController@viewassignhotelclient')->name('trip.hotel.viewassignhotelclient');

    Route::post('trip/hotel/viewHotelTripByCustomerID', 'TripHotelController@viewHotelTripByCustomerID')->name('view.trip.hotel.viewHotelTripByCustomerID');

    Route::post('trip/customer/hotel', 'TripHotelController@assignHotelToSingleCustomer')->name('assign.hotel.single.customer');


    //Route::get('trip/test/{trip}', 'TripHotelController@test');

    //send push notification
    Route::get('/push_notification/{trip}', 'TripPushNotificationController@index')->name('trip.notification.index');
    Route::post('/push_notification', 'TripPushNotificationController@store')->name('trip.notification.store');

    //upload client with excel sheet
    Route::get('/excelupload', 'TripPushNotificationController@loadExcelView')->name('load.excel.view');
    Route::post('/excelupload/store', 'TripPushNotificationController@storeExcelSheet')->name('load.excel.store');
    Route::post('/excelupload/storestaff', 'TripPushNotificationController@storeExcelSheetForStaff')->name('load.excel.storestaff');

    Route::get('/excelupload/downloadclient', 'TripPushNotificationController@downloadclient')->name('load.excel.downloadclient');

    Route::get('/excelupload/downloadstaff', 'TripPushNotificationController@downloadstaff')->name('load.excel.downloadstaff');

    //Route for messages
    Route::get('trip/client/messages', 'TripMessageController@index')->name('trip.client.message');

    Route::post('load/client/message', 'TripMessageController@loadClientMessages')->name('load.client.message');

    Route::post('load/client', 'TripMessageController@loadClient')->name('load.client');

    Route::post('trip/client/messages', 'TripMessageController@showmessage')->name('trip.client.showmessage');

    Route::post('/send/messages', 'TripMessageController@sendMessages')->name('send.message');

    //Route for Trip airline
    Route::get('trip/flight/{trip}', 'TripFlightController@index')->name('trip.flight');
    Route::post('/trip/flight/store', 'TripFlightController@addFlightForTrip')->name('trip.flight.store');

    Route::get('trip/flight/viewassignclient/{flightid}', 'TripFlightController@viewassignclient')->name('trip.flight.viewassignclient');

    Route::delete('/trip/flight/destroy/{id}', 'TripFlightController@destroy')->name('trip.flight.destroy');

    Route::post('trip/flight/customerbyid', 'TripFlightController@viewTripByCustomerID')->name('view.trip.flight.customerbyid');
    Route::post('/trip/flight/customer/store', 'TripFlightController@updateFlightForCustomer')->name('trip.flight.customer.store');
    Route::post('/trip/flight/deleteflightbyid', 'TripFlightController@deleteflightbyid')->name('trip.flight.deleteflightbyid');

    //Route for trip tasks
    //Route::get('trip/task/{trip}', 'TripTaskController@index')->name('trip.task');
    Route::get('/trip/task/index', 'TripTaskController@index')->name('trip.task.index');
    Route::get('/trip/task/create', 'TripTaskController@create')->name('trip.task.create');
    Route::post('/trip/task/store', 'TripTaskController@addTasks')->name('trip.task.store');
    Route::delete('/trip/task/destroy/{id}', 'TripTaskController@destroy')->name('trip.task.destroy');
    Route::get('/trip/task/edit/{id}', 'TripTaskController@edit')->name('trip.task.edit');
    Route::post('/trip/task/update', 'TripTaskController@update')->name('trip.task.update');
    Route::get('/trip/task/stafftaskoverduedetail/{id}', 'TripTaskController@stafftaskoverduedetail')->name('trip.task.stafftaskoverduedetail');
    Route::get('/trip/task/customertaskoverduedetail/{id}', 'TripTaskController@customertaskoverduedetail')->name('trip.task.customertaskoverduedetail');

app/EmergencyAlert.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Camroncade\Timezone\Facades\Timezone;
use Carbon\Carbon;
class EmergencyAlert extends Model
{
    protected $guarded = [];
	/**
     * Scope a query to only include logged in users trips.
     *
     * @param  \Illuminate\Database\Eloquent\Builder  $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeLoggedTravelAgency($query)
    {
    	if(\Auth::user()->user_type == 'agent' || \Auth::user()->user_type == 'staff' || \Auth::user()->user_type == 'mobile_agent')
        	return $query->where('travel_agency_id', \Auth::user()->userType->travel_agency_id);
        return $query;
    }

    public function clientgtouptrip(){
        return $this->belongsTo(GroupClientTrip::class,'client_trip_id');
    }

    public function getCreatedAtAttribute()
    {
        return Carbon::parse($this->attributes['created_at'])->setTimezone(\Auth::user()->time_zone);
    }
}

app/Http/Controllers/API/V1/Client/EmergencyAlertController.php
<?php

namespace App\Http\Controllers\API\V1\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\EmergencyAlert;
use Utils;
use Carbon\Carbon;

class EmergencyAlertController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($client_trip_id)
    {
        return EmergencyAlert::where('client_trip_id', $client_trip_id)->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $client_trip_id)
    {
        $CurrentDate=date('Y-m-d');
        $current = Carbon::now();
        $request->validate([
            // 'client_trip_id'    => 'required|exists:client_trips,id',
            // 'message'           => 'required',
            'lat'               => 'required|numeric',
            'lon'               => 'required|numeric',
        ]);

//        if(\Auth::user()->userType->id != \App\ClientTrip::find($client_trip_id)->id)
//            return abort(403);

        $emergency_alert                 = new EmergencyAlert;
        $emergency_alert->client_trip_id = $client_trip_id;
        // $emergency_alert->message        = $request->message;
        $emergency_alert->lat            = $request->lat;
        $emergency_alert->lon            = $request->lon;
        $emergency_alert->save();

        /* Send Push to All Agents */
        $user_ids       = \App\Agent::where('travel_agency_id', Utils::tripByClientTrip($client_trip_id)->travel_agency_id)->pluck('user_id');
        $fcms           = \App\User::whereIn('id', $user_ids)->pluck('fcm_token');

        $body           = array('type' => "emergency_alert" , 'data' => ['message' => "Emergency Alert Recevied."]);

        foreach($fcms as $fcm)
        {
            Utils::sendNotification($fcm, $body);
        }

        return response()->json(['status' => true, 'message' => 'Alert has been received, we will get back to you soon']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(EmergencyAlert $id)
    {
        return $id;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, EmergencyAlert $id)
    {
        $request->validate([
            // 'client_trip_id'    => 'required|exists:client_trips,id',
            // 'message'           => 'required',
            'lat'               => 'required|numeric',
            'lon'               => 'required|numeric',
        ]);

        $emergency_alert                 = $id;
        // $emergency_alert->client_trip_id = $request->client_trip_id;
        // $emergency_alert->message        = $request->message;
        $emergency_alert->lat            = $request->lat;
        $emergency_alert->lon            = $request->lon;
        $emergency_alert->save();

        return;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(EmergencyAlert $id)
    {
        $id->delete();
    }
}

app/Http/Controllers/EmergencyAlertController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\EmergencyAlert;
use App\TripUpdate;

class EmergencyAlertController extends Controller
{
    public function index($type = 'all')
    {
       $emergency_alerts= EmergencyAlert::with(['clientgtouptrip.clienttrip.group'])
                                          ->whereHas('clientgtouptrip.client',function($q){
                                            $q->where('travel_agency_id',Auth()->user()->userType->travel_agency_id);
                                          })
                                          ->orderBy('id','DESC')->get();
                                         
       //return $emergency_alerts;
    	//$client_trip_ids = \App\ClientTrip::whereIn('trip_id', \App\Trip::loggedTravelAgency()->pluck('id'))->pluck('id');
    	//if($type == 'all')
    	//{
    		//$emergency_alerts = EmergencyAlert::whereIn('client_trip_id', $client_trip_ids)
    		//									->get();
    	//}
    	//else
    	//{
    	//	$emergency_alerts = EmergencyAlert::whereIn('client_trip_id', $client_trip_ids)
    	//										->where('status', 'sent')
    	//											->get();
        //}
    	return view('emergency_alert.index', compact("emergency_alerts"));
    }

    public function update(Request $request, $id)
    {
    	$request->validate([
    		'status'	=> "required|in:seen,solved"
    	]);

    	$emergency_alert 			= EmergencyAlert::findOrFail($id);
    	$emergency_alert->status 	= $request->status;
    	$emergency_alert->save();

    	return back()->with(['status' => "success", 'message' => "Status Updated."]);
    }
}

resources/views/emergency_alert/index.blade.php
@extends('adminlte::page')
@section('title', 'All Alerts')

@section('content_header')
    <h1>All Alerts</h1>
    <div class="clearfix"></div>
    {{-- <ol class="breadcrumb">
        <li><a href="{{ URL::previous() }}">Back</a></li>
    </ol> --}}
@endsection


@section('content')
    <div class="box">
        <div class="box-body">
            <table id="emergencyAlerts" class="table table-bordered">
                <thead>
                <tr>
                    <th>Sr#</th>
                    @if(\Auth::user()->user_type == "super_admin")
                        <th>Travel Agency</th>
                    @endif
                    <th>Client</th>
                    <th>Trip</th>
                    <th>Catagory</th>
                    <th>Group</th>
                    <th>Phone Main</th>
                    <th>Phone Backup</th>
                    <th>Phone Emergency</th>
                    <th>Status</th>
                    <th>Sent Time</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($emergency_alerts as $emergency_alert)
                @if($emergency_alert->status == 'solved')
                    <tr style="background-color: #90EE90">
                        <td>{{ $loop->iteration }}</td>
                        @if(\Auth::user()->user_type == "super_admin")
                            <td>
                                <a href="{{ route('travel_agency.show', ['id' => Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->agency_name }}</a>
                            </td>
                        @endif
                        <td>
                            <a href="{{ route('clients.showprofile', ['id' => Utils::clientByClientTrip($emergency_alert->client_trip_id)->user_id]) }}" target="_blank">{{ Utils::clientByClientTrip($emergency_alert->client_trip_id)->getFullName() }}</a>
                        </td>
                        <td>{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</td>
                       {{-- <td>
                            <a href="{{ route('trips.show', ['id' => Utils::tripByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</a>
                        </td>--}}
                        <td>{{$emergency_alert->clientgtouptrip->client->client_category->title ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->clienttrip->group->group_name ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->primary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->secondary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->emergency_phone_number ?? '--'}}</td>
                        <td>
                            <button class="btn btn-xs btn-{{ $emergency_alert->status == 'sent' ? 'danger' : ($emergency_alert->status == 'seen' ? 'warning' : 'success') }}">{{ $emergency_alert->status == 'sent' ? 'New' : ($emergency_alert->status == 'seen' ? 'Seen' : 'Resolved') }}</button>
                        </td>
                        <td>{{ $emergency_alert->created_at->format('Y-m-d h:i:s a') }}</td>
                        <td>
                            {{-- <a href="{{ route('clients.edit', ['id' => $client->user_id]) }}"><button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i></button></a> --}}
                            <a target="_blank" href="https://www.google.com/maps?q={{ $emergency_alert->lat }},{{ $emergency_alert->lon }}">
                                <button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Location"><i class="fa fa-map-pin"></i></button>
                            </a>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="seen">
                                <button type="submit" class="btn btn-xs btn-warning" data-toggle="tooltip" title="Mark As Seen"><i class="fa fa-eye"></i></button>
                            </form>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="solved">
                                <button type="submit" class="btn btn-xs btn-success" data-toggle="tooltip" title="Mark As Solved"><i class="fa fa-check"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endif
                    @if($emergency_alert->status == 'seen')
                    <tr style="background-color: #F5F5F5">
                        <td>{{ $loop->iteration }}</td>
                        @if(\Auth::user()->user_type == "super_admin")
                            <td>
                                <a href="{{ route('travel_agency.show', ['id' => Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->agency_name }}</a>
                            </td>
                        @endif
                        <td>
                            <a href="{{ route('clients.showprofile', ['id' => Utils::clientByClientTrip($emergency_alert->client_trip_id)->user_id]) }}" target="_blank">{{ Utils::clientByClientTrip($emergency_alert->client_trip_id)->getFullName() }}</a>
                        </td>
                        <td>{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</td>
                       {{-- <td>
                            <a href="{{ route('trips.show', ['id' => Utils::tripByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</a>
                        </td>--}}
                        <td>{{$emergency_alert->clientgtouptrip->client->client_category->title ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->clienttrip->group->group_name ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->primary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->secondary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->emergency_phone_number ?? '--'}}</td>
                        <td>
                            <button class="btn btn-xs btn-{{ $emergency_alert->status == 'sent' ? 'danger' : ($emergency_alert->status == 'seen' ? 'warning' : 'success') }}">{{ $emergency_alert->status == 'sent' ? 'New' : ($emergency_alert->status == 'seen' ? 'Seen' : 'Resolved') }}</button>
                        </td>
                        <td>{{ $emergency_alert->created_at->format('Y-m-d h:i:s a') }}</td>
                        <td>
                            {{-- <a href="{{ route('clients.edit', ['id' => $client->user_id]) }}"><button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i></button></a> --}}
                            <a target="_blank" href="https://www.google.com/maps?q={{ $emergency_alert->lat }},{{ $emergency_alert->lon }}">
                                <button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Location"><i class="fa fa-map-pin"></i></button>
                            </a>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="seen">
                                <button type="submit" class="btn btn-xs btn-warning" data-toggle="tooltip" title="Mark As Seen"><i class="fa fa-eye"></i></button>
                            </form>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="solved">
                                <button type="submit" class="btn btn-xs btn-success" data-toggle="tooltip" title="Mark As Solved"><i class="fa fa-check"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endif
                    @if($emergency_alert->status == 'sent')
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        @if(\Auth::user()->user_type == "super_admin")
                            <td>
                                <a href="{{ route('travel_agency.show', ['id' => Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::travelAgencyByClientTrip($emergency_alert->client_trip_id)->agency_name }}</a>
                            </td>
                        @endif
                        <td>
                            <a href="{{ route('clients.showprofile', ['id' => Utils::clientByClientTrip($emergency_alert->client_trip_id)->user_id]) }}" target="_blank">{{ Utils::clientByClientTrip($emergency_alert->client_trip_id)->getFullName() }}</a>
                        </td>
                        <td>{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</td>
                       {{-- <td>
                            <a href="{{ route('trips.show', ['id' => Utils::tripByClientTrip($emergency_alert->client_trip_id)->id]) }}">{{ Utils::tripByClientTrip($emergency_alert->client_trip_id)->title }}</a>
                        </td>--}}
                        <td>{{$emergency_alert->clientgtouptrip->client->client_category->title ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->clienttrip->group->group_name ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->primary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->secondary_phone_number ?? '--'}}</td>
                        <td>{{$emergency_alert->clientgtouptrip->client->emergency_phone_number ?? '--'}}</td>
                        <td>
                            <button class="btn btn-xs btn-{{ $emergency_alert->status == 'sent' ? 'danger' : ($emergency_alert->status == 'seen' ? 'warning' : 'success') }}">{{ $emergency_alert->status == 'sent' ? 'New' : ($emergency_alert->status == 'seen' ? 'Seen' : 'Resolved') }}</button>
                        </td>
                        <td>{{ $emergency_alert->created_at->format('Y-m-d h:i:s a') }}</td>
                        <td>
                            {{-- <a href="{{ route('clients.edit', ['id' => $client->user_id]) }}"><button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Edit"><i class="fa fa-pencil"></i></button></a> --}}
                            <a target="_blank" href="https://www.google.com/maps?q={{ $emergency_alert->lat }},{{ $emergency_alert->lon }}">
                                <button class="btn btn-xs btn-primary" data-toggle="tooltip" title="Location"><i class="fa fa-map-pin"></i></button>
                            </a>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="seen">
                                <button type="submit" class="btn btn-xs btn-warning" data-toggle="tooltip" title="Mark As Seen"><i class="fa fa-eye"></i></button>
                            </form>
                            <form action="{{ route('emergency_alert.update', ['id' => $emergency_alert->id]) }}" method="POST" class="delete_item">
                                @csrf
                                @method('PUT')
                                <input type="hidden" name="status" value="solved">
                                <button type="submit" class="btn btn-xs btn-success" data-toggle="tooltip" title="Mark As Solved"><i class="fa fa-check"></i></button>
                            </form>
                        </td>
                    </tr>
                    @endif

                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
@endsection

@push('js')
    <script type="text/javascript">
        $(function () {
            $('#emergencyAlerts').DataTable({
                'lengthChange': false,
                "columnDefs": [
                 { orderable: false, targets:10 },
                 ],
            })
            $('form.delete_item').unbind('submit');
        });
    </script>
@endpush